package com.baoluoge.exam.dao.paper;


import com.baoluoge.exam.domain.ExamPaper;
import com.baoluoge.exam.domain.ExamPaperExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ExamPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    long countByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    int deleteByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    int insert(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    int insertSelective(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    List<ExamPaper> selectByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    ExamPaper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") ExamPaper record, @Param("example") ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    int updateByExample(@Param("record") ExamPaper record, @Param("example") ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    int updateByPrimaryKeySelective(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    int updateByPrimaryKey(ExamPaper record);
}