server:
  port: 8761 # eureka instance port
eureka:
  instance:
    hostname: com.baoluoge.discovery # eureka instance host name
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
