spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhangPengPaul/config-repo
          username:
          password:
server:
  port: 8888

eureka:
  client:
    service-url:
     defaultZone: http://com.baoluoge.discovery:8761/eureka/
    healthcheck:
      enabled: true
