package com.baoluoge.exam.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExamQuestionNarrowExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    public ExamQuestionNarrowExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdIsNull() {
            addCriterion("exam_questions_broad_id is null");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdIsNotNull() {
            addCriterion("exam_questions_broad_id is not null");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdEqualTo(Integer value) {
            addCriterion("exam_questions_broad_id =", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdNotEqualTo(Integer value) {
            addCriterion("exam_questions_broad_id <>", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdGreaterThan(Integer value) {
            addCriterion("exam_questions_broad_id >", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("exam_questions_broad_id >=", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdLessThan(Integer value) {
            addCriterion("exam_questions_broad_id <", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdLessThanOrEqualTo(Integer value) {
            addCriterion("exam_questions_broad_id <=", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdIn(List<Integer> values) {
            addCriterion("exam_questions_broad_id in", values, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdNotIn(List<Integer> values) {
            addCriterion("exam_questions_broad_id not in", values, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdBetween(Integer value1, Integer value2) {
            addCriterion("exam_questions_broad_id between", value1, value2, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdNotBetween(Integer value1, Integer value2) {
            addCriterion("exam_questions_broad_id not between", value1, value2, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andBeforeBindNarrowIdIsNull() {
            addCriterion("before_bind_narrow_id is null");
            return (Criteria) this;
        }

        public Criteria andBeforeBindNarrowIdIsNotNull() {
            addCriterion("before_bind_narrow_id is not null");
            return (Criteria) this;
        }

        public Criteria andBeforeBindNarrowIdEqualTo(Integer value) {
            addCriterion("before_bind_narrow_id =", value, "beforeBindNarrowId");
            return (Criteria) this;
        }

        public Criteria andBeforeBindNarrowIdNotEqualTo(Integer value) {
            addCriterion("before_bind_narrow_id <>", value, "beforeBindNarrowId");
            return (Criteria) this;
        }

        public Criteria andBeforeBindNarrowIdGreaterThan(Integer value) {
            addCriterion("before_bind_narrow_id >", value, "beforeBindNarrowId");
            return (Criteria) this;
        }

        public Criteria andBeforeBindNarrowIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("before_bind_narrow_id >=", value, "beforeBindNarrowId");
            return (Criteria) this;
        }

        public Criteria andBeforeBindNarrowIdLessThan(Integer value) {
            addCriterion("before_bind_narrow_id <", value, "beforeBindNarrowId");
            return (Criteria) this;
        }

        public Criteria andBeforeBindNarrowIdLessThanOrEqualTo(Integer value) {
            addCriterion("before_bind_narrow_id <=", value, "beforeBindNarrowId");
            return (Criteria) this;
        }

        public Criteria andBeforeBindNarrowIdIn(List<Integer> values) {
            addCriterion("before_bind_narrow_id in", values, "beforeBindNarrowId");
            return (Criteria) this;
        }

        public Criteria andBeforeBindNarrowIdNotIn(List<Integer> values) {
            addCriterion("before_bind_narrow_id not in", values, "beforeBindNarrowId");
            return (Criteria) this;
        }

        public Criteria andBeforeBindNarrowIdBetween(Integer value1, Integer value2) {
            addCriterion("before_bind_narrow_id between", value1, value2, "beforeBindNarrowId");
            return (Criteria) this;
        }

        public Criteria andBeforeBindNarrowIdNotBetween(Integer value1, Integer value2) {
            addCriterion("before_bind_narrow_id not between", value1, value2, "beforeBindNarrowId");
            return (Criteria) this;
        }

        public Criteria andCodeNumberIsNull() {
            addCriterion("code_number is null");
            return (Criteria) this;
        }

        public Criteria andCodeNumberIsNotNull() {
            addCriterion("code_number is not null");
            return (Criteria) this;
        }

        public Criteria andCodeNumberEqualTo(String value) {
            addCriterion("code_number =", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberNotEqualTo(String value) {
            addCriterion("code_number <>", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberGreaterThan(String value) {
            addCriterion("code_number >", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberGreaterThanOrEqualTo(String value) {
            addCriterion("code_number >=", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberLessThan(String value) {
            addCriterion("code_number <", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberLessThanOrEqualTo(String value) {
            addCriterion("code_number <=", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberLike(String value) {
            addCriterion("code_number like", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberNotLike(String value) {
            addCriterion("code_number not like", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberIn(List<String> values) {
            addCriterion("code_number in", values, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberNotIn(List<String> values) {
            addCriterion("code_number not in", values, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberBetween(String value1, String value2) {
            addCriterion("code_number between", value1, value2, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberNotBetween(String value1, String value2) {
            addCriterion("code_number not between", value1, value2, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andOrderIsNull() {
            addCriterion("`order` is null");
            return (Criteria) this;
        }

        public Criteria andOrderIsNotNull() {
            addCriterion("`order` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderEqualTo(Integer value) {
            addCriterion("`order` =", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotEqualTo(Integer value) {
            addCriterion("`order` <>", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderGreaterThan(Integer value) {
            addCriterion("`order` >", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("`order` >=", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderLessThan(Integer value) {
            addCriterion("`order` <", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderLessThanOrEqualTo(Integer value) {
            addCriterion("`order` <=", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderIn(List<Integer> values) {
            addCriterion("`order` in", values, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotIn(List<Integer> values) {
            addCriterion("`order` not in", values, "order");
            return (Criteria) this;
        }

        public Criteria andOrderBetween(Integer value1, Integer value2) {
            addCriterion("`order` between", value1, value2, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("`order` not between", value1, value2, "order");
            return (Criteria) this;
        }

        public Criteria andShowTypeIsNull() {
            addCriterion("show_type is null");
            return (Criteria) this;
        }

        public Criteria andShowTypeIsNotNull() {
            addCriterion("show_type is not null");
            return (Criteria) this;
        }

        public Criteria andShowTypeEqualTo(Integer value) {
            addCriterion("show_type =", value, "showType");
            return (Criteria) this;
        }

        public Criteria andShowTypeNotEqualTo(Integer value) {
            addCriterion("show_type <>", value, "showType");
            return (Criteria) this;
        }

        public Criteria andShowTypeGreaterThan(Integer value) {
            addCriterion("show_type >", value, "showType");
            return (Criteria) this;
        }

        public Criteria andShowTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("show_type >=", value, "showType");
            return (Criteria) this;
        }

        public Criteria andShowTypeLessThan(Integer value) {
            addCriterion("show_type <", value, "showType");
            return (Criteria) this;
        }

        public Criteria andShowTypeLessThanOrEqualTo(Integer value) {
            addCriterion("show_type <=", value, "showType");
            return (Criteria) this;
        }

        public Criteria andShowTypeIn(List<Integer> values) {
            addCriterion("show_type in", values, "showType");
            return (Criteria) this;
        }

        public Criteria andShowTypeNotIn(List<Integer> values) {
            addCriterion("show_type not in", values, "showType");
            return (Criteria) this;
        }

        public Criteria andShowTypeBetween(Integer value1, Integer value2) {
            addCriterion("show_type between", value1, value2, "showType");
            return (Criteria) this;
        }

        public Criteria andShowTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("show_type not between", value1, value2, "showType");
            return (Criteria) this;
        }

        public Criteria andTitleContentIsNull() {
            addCriterion("title_content is null");
            return (Criteria) this;
        }

        public Criteria andTitleContentIsNotNull() {
            addCriterion("title_content is not null");
            return (Criteria) this;
        }

        public Criteria andTitleContentEqualTo(String value) {
            addCriterion("title_content =", value, "titleContent");
            return (Criteria) this;
        }

        public Criteria andTitleContentNotEqualTo(String value) {
            addCriterion("title_content <>", value, "titleContent");
            return (Criteria) this;
        }

        public Criteria andTitleContentGreaterThan(String value) {
            addCriterion("title_content >", value, "titleContent");
            return (Criteria) this;
        }

        public Criteria andTitleContentGreaterThanOrEqualTo(String value) {
            addCriterion("title_content >=", value, "titleContent");
            return (Criteria) this;
        }

        public Criteria andTitleContentLessThan(String value) {
            addCriterion("title_content <", value, "titleContent");
            return (Criteria) this;
        }

        public Criteria andTitleContentLessThanOrEqualTo(String value) {
            addCriterion("title_content <=", value, "titleContent");
            return (Criteria) this;
        }

        public Criteria andTitleContentLike(String value) {
            addCriterion("title_content like", value, "titleContent");
            return (Criteria) this;
        }

        public Criteria andTitleContentNotLike(String value) {
            addCriterion("title_content not like", value, "titleContent");
            return (Criteria) this;
        }

        public Criteria andTitleContentIn(List<String> values) {
            addCriterion("title_content in", values, "titleContent");
            return (Criteria) this;
        }

        public Criteria andTitleContentNotIn(List<String> values) {
            addCriterion("title_content not in", values, "titleContent");
            return (Criteria) this;
        }

        public Criteria andTitleContentBetween(String value1, String value2) {
            addCriterion("title_content between", value1, value2, "titleContent");
            return (Criteria) this;
        }

        public Criteria andTitleContentNotBetween(String value1, String value2) {
            addCriterion("title_content not between", value1, value2, "titleContent");
            return (Criteria) this;
        }

        public Criteria andTitleDescIsNull() {
            addCriterion("title_desc is null");
            return (Criteria) this;
        }

        public Criteria andTitleDescIsNotNull() {
            addCriterion("title_desc is not null");
            return (Criteria) this;
        }

        public Criteria andTitleDescEqualTo(String value) {
            addCriterion("title_desc =", value, "titleDesc");
            return (Criteria) this;
        }

        public Criteria andTitleDescNotEqualTo(String value) {
            addCriterion("title_desc <>", value, "titleDesc");
            return (Criteria) this;
        }

        public Criteria andTitleDescGreaterThan(String value) {
            addCriterion("title_desc >", value, "titleDesc");
            return (Criteria) this;
        }

        public Criteria andTitleDescGreaterThanOrEqualTo(String value) {
            addCriterion("title_desc >=", value, "titleDesc");
            return (Criteria) this;
        }

        public Criteria andTitleDescLessThan(String value) {
            addCriterion("title_desc <", value, "titleDesc");
            return (Criteria) this;
        }

        public Criteria andTitleDescLessThanOrEqualTo(String value) {
            addCriterion("title_desc <=", value, "titleDesc");
            return (Criteria) this;
        }

        public Criteria andTitleDescLike(String value) {
            addCriterion("title_desc like", value, "titleDesc");
            return (Criteria) this;
        }

        public Criteria andTitleDescNotLike(String value) {
            addCriterion("title_desc not like", value, "titleDesc");
            return (Criteria) this;
        }

        public Criteria andTitleDescIn(List<String> values) {
            addCriterion("title_desc in", values, "titleDesc");
            return (Criteria) this;
        }

        public Criteria andTitleDescNotIn(List<String> values) {
            addCriterion("title_desc not in", values, "titleDesc");
            return (Criteria) this;
        }

        public Criteria andTitleDescBetween(String value1, String value2) {
            addCriterion("title_desc between", value1, value2, "titleDesc");
            return (Criteria) this;
        }

        public Criteria andTitleDescNotBetween(String value1, String value2) {
            addCriterion("title_desc not between", value1, value2, "titleDesc");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlIsNull() {
            addCriterion("title_img_url is null");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlIsNotNull() {
            addCriterion("title_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlEqualTo(String value) {
            addCriterion("title_img_url =", value, "titleImgUrl");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlNotEqualTo(String value) {
            addCriterion("title_img_url <>", value, "titleImgUrl");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlGreaterThan(String value) {
            addCriterion("title_img_url >", value, "titleImgUrl");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("title_img_url >=", value, "titleImgUrl");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlLessThan(String value) {
            addCriterion("title_img_url <", value, "titleImgUrl");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlLessThanOrEqualTo(String value) {
            addCriterion("title_img_url <=", value, "titleImgUrl");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlLike(String value) {
            addCriterion("title_img_url like", value, "titleImgUrl");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlNotLike(String value) {
            addCriterion("title_img_url not like", value, "titleImgUrl");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlIn(List<String> values) {
            addCriterion("title_img_url in", values, "titleImgUrl");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlNotIn(List<String> values) {
            addCriterion("title_img_url not in", values, "titleImgUrl");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlBetween(String value1, String value2) {
            addCriterion("title_img_url between", value1, value2, "titleImgUrl");
            return (Criteria) this;
        }

        public Criteria andTitleImgUrlNotBetween(String value1, String value2) {
            addCriterion("title_img_url not between", value1, value2, "titleImgUrl");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextIsNull() {
            addCriterion("title_audio_text is null");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextIsNotNull() {
            addCriterion("title_audio_text is not null");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextEqualTo(String value) {
            addCriterion("title_audio_text =", value, "titleAudioText");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextNotEqualTo(String value) {
            addCriterion("title_audio_text <>", value, "titleAudioText");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextGreaterThan(String value) {
            addCriterion("title_audio_text >", value, "titleAudioText");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextGreaterThanOrEqualTo(String value) {
            addCriterion("title_audio_text >=", value, "titleAudioText");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextLessThan(String value) {
            addCriterion("title_audio_text <", value, "titleAudioText");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextLessThanOrEqualTo(String value) {
            addCriterion("title_audio_text <=", value, "titleAudioText");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextLike(String value) {
            addCriterion("title_audio_text like", value, "titleAudioText");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextNotLike(String value) {
            addCriterion("title_audio_text not like", value, "titleAudioText");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextIn(List<String> values) {
            addCriterion("title_audio_text in", values, "titleAudioText");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextNotIn(List<String> values) {
            addCriterion("title_audio_text not in", values, "titleAudioText");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextBetween(String value1, String value2) {
            addCriterion("title_audio_text between", value1, value2, "titleAudioText");
            return (Criteria) this;
        }

        public Criteria andTitleAudioTextNotBetween(String value1, String value2) {
            addCriterion("title_audio_text not between", value1, value2, "titleAudioText");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathIsNull() {
            addCriterion("title_audio_path is null");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathIsNotNull() {
            addCriterion("title_audio_path is not null");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathEqualTo(String value) {
            addCriterion("title_audio_path =", value, "titleAudioPath");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathNotEqualTo(String value) {
            addCriterion("title_audio_path <>", value, "titleAudioPath");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathGreaterThan(String value) {
            addCriterion("title_audio_path >", value, "titleAudioPath");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathGreaterThanOrEqualTo(String value) {
            addCriterion("title_audio_path >=", value, "titleAudioPath");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathLessThan(String value) {
            addCriterion("title_audio_path <", value, "titleAudioPath");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathLessThanOrEqualTo(String value) {
            addCriterion("title_audio_path <=", value, "titleAudioPath");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathLike(String value) {
            addCriterion("title_audio_path like", value, "titleAudioPath");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathNotLike(String value) {
            addCriterion("title_audio_path not like", value, "titleAudioPath");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathIn(List<String> values) {
            addCriterion("title_audio_path in", values, "titleAudioPath");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathNotIn(List<String> values) {
            addCriterion("title_audio_path not in", values, "titleAudioPath");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathBetween(String value1, String value2) {
            addCriterion("title_audio_path between", value1, value2, "titleAudioPath");
            return (Criteria) this;
        }

        public Criteria andTitleAudioPathNotBetween(String value1, String value2) {
            addCriterion("title_audio_path not between", value1, value2, "titleAudioPath");
            return (Criteria) this;
        }

        public Criteria andTitleAudioRepeatTimesIsNull() {
            addCriterion("title_audio_repeat_times is null");
            return (Criteria) this;
        }

        public Criteria andTitleAudioRepeatTimesIsNotNull() {
            addCriterion("title_audio_repeat_times is not null");
            return (Criteria) this;
        }

        public Criteria andTitleAudioRepeatTimesEqualTo(Integer value) {
            addCriterion("title_audio_repeat_times =", value, "titleAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andTitleAudioRepeatTimesNotEqualTo(Integer value) {
            addCriterion("title_audio_repeat_times <>", value, "titleAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andTitleAudioRepeatTimesGreaterThan(Integer value) {
            addCriterion("title_audio_repeat_times >", value, "titleAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andTitleAudioRepeatTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("title_audio_repeat_times >=", value, "titleAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andTitleAudioRepeatTimesLessThan(Integer value) {
            addCriterion("title_audio_repeat_times <", value, "titleAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andTitleAudioRepeatTimesLessThanOrEqualTo(Integer value) {
            addCriterion("title_audio_repeat_times <=", value, "titleAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andTitleAudioRepeatTimesIn(List<Integer> values) {
            addCriterion("title_audio_repeat_times in", values, "titleAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andTitleAudioRepeatTimesNotIn(List<Integer> values) {
            addCriterion("title_audio_repeat_times not in", values, "titleAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andTitleAudioRepeatTimesBetween(Integer value1, Integer value2) {
            addCriterion("title_audio_repeat_times between", value1, value2, "titleAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andTitleAudioRepeatTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("title_audio_repeat_times not between", value1, value2, "titleAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andTitleWaittimeMillsecondsIsNull() {
            addCriterion("title_waittime_millseconds is null");
            return (Criteria) this;
        }

        public Criteria andTitleWaittimeMillsecondsIsNotNull() {
            addCriterion("title_waittime_millseconds is not null");
            return (Criteria) this;
        }

        public Criteria andTitleWaittimeMillsecondsEqualTo(Long value) {
            addCriterion("title_waittime_millseconds =", value, "titleWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andTitleWaittimeMillsecondsNotEqualTo(Long value) {
            addCriterion("title_waittime_millseconds <>", value, "titleWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andTitleWaittimeMillsecondsGreaterThan(Long value) {
            addCriterion("title_waittime_millseconds >", value, "titleWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andTitleWaittimeMillsecondsGreaterThanOrEqualTo(Long value) {
            addCriterion("title_waittime_millseconds >=", value, "titleWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andTitleWaittimeMillsecondsLessThan(Long value) {
            addCriterion("title_waittime_millseconds <", value, "titleWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andTitleWaittimeMillsecondsLessThanOrEqualTo(Long value) {
            addCriterion("title_waittime_millseconds <=", value, "titleWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andTitleWaittimeMillsecondsIn(List<Long> values) {
            addCriterion("title_waittime_millseconds in", values, "titleWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andTitleWaittimeMillsecondsNotIn(List<Long> values) {
            addCriterion("title_waittime_millseconds not in", values, "titleWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andTitleWaittimeMillsecondsBetween(Long value1, Long value2) {
            addCriterion("title_waittime_millseconds between", value1, value2, "titleWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andTitleWaittimeMillsecondsNotBetween(Long value1, Long value2) {
            addCriterion("title_waittime_millseconds not between", value1, value2, "titleWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andDescContentIsNull() {
            addCriterion("desc_content is null");
            return (Criteria) this;
        }

        public Criteria andDescContentIsNotNull() {
            addCriterion("desc_content is not null");
            return (Criteria) this;
        }

        public Criteria andDescContentEqualTo(String value) {
            addCriterion("desc_content =", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentNotEqualTo(String value) {
            addCriterion("desc_content <>", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentGreaterThan(String value) {
            addCriterion("desc_content >", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentGreaterThanOrEqualTo(String value) {
            addCriterion("desc_content >=", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentLessThan(String value) {
            addCriterion("desc_content <", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentLessThanOrEqualTo(String value) {
            addCriterion("desc_content <=", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentLike(String value) {
            addCriterion("desc_content like", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentNotLike(String value) {
            addCriterion("desc_content not like", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentIn(List<String> values) {
            addCriterion("desc_content in", values, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentNotIn(List<String> values) {
            addCriterion("desc_content not in", values, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentBetween(String value1, String value2) {
            addCriterion("desc_content between", value1, value2, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentNotBetween(String value1, String value2) {
            addCriterion("desc_content not between", value1, value2, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlIsNull() {
            addCriterion("desc_img_url is null");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlIsNotNull() {
            addCriterion("desc_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlEqualTo(String value) {
            addCriterion("desc_img_url =", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlNotEqualTo(String value) {
            addCriterion("desc_img_url <>", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlGreaterThan(String value) {
            addCriterion("desc_img_url >", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("desc_img_url >=", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlLessThan(String value) {
            addCriterion("desc_img_url <", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlLessThanOrEqualTo(String value) {
            addCriterion("desc_img_url <=", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlLike(String value) {
            addCriterion("desc_img_url like", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlNotLike(String value) {
            addCriterion("desc_img_url not like", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlIn(List<String> values) {
            addCriterion("desc_img_url in", values, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlNotIn(List<String> values) {
            addCriterion("desc_img_url not in", values, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlBetween(String value1, String value2) {
            addCriterion("desc_img_url between", value1, value2, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlNotBetween(String value1, String value2) {
            addCriterion("desc_img_url not between", value1, value2, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextIsNull() {
            addCriterion("desc_audio_text is null");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextIsNotNull() {
            addCriterion("desc_audio_text is not null");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextEqualTo(String value) {
            addCriterion("desc_audio_text =", value, "descAudioText");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextNotEqualTo(String value) {
            addCriterion("desc_audio_text <>", value, "descAudioText");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextGreaterThan(String value) {
            addCriterion("desc_audio_text >", value, "descAudioText");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextGreaterThanOrEqualTo(String value) {
            addCriterion("desc_audio_text >=", value, "descAudioText");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextLessThan(String value) {
            addCriterion("desc_audio_text <", value, "descAudioText");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextLessThanOrEqualTo(String value) {
            addCriterion("desc_audio_text <=", value, "descAudioText");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextLike(String value) {
            addCriterion("desc_audio_text like", value, "descAudioText");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextNotLike(String value) {
            addCriterion("desc_audio_text not like", value, "descAudioText");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextIn(List<String> values) {
            addCriterion("desc_audio_text in", values, "descAudioText");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextNotIn(List<String> values) {
            addCriterion("desc_audio_text not in", values, "descAudioText");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextBetween(String value1, String value2) {
            addCriterion("desc_audio_text between", value1, value2, "descAudioText");
            return (Criteria) this;
        }

        public Criteria andDescAudioTextNotBetween(String value1, String value2) {
            addCriterion("desc_audio_text not between", value1, value2, "descAudioText");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathIsNull() {
            addCriterion("desc_audio_path is null");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathIsNotNull() {
            addCriterion("desc_audio_path is not null");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathEqualTo(String value) {
            addCriterion("desc_audio_path =", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathNotEqualTo(String value) {
            addCriterion("desc_audio_path <>", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathGreaterThan(String value) {
            addCriterion("desc_audio_path >", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathGreaterThanOrEqualTo(String value) {
            addCriterion("desc_audio_path >=", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathLessThan(String value) {
            addCriterion("desc_audio_path <", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathLessThanOrEqualTo(String value) {
            addCriterion("desc_audio_path <=", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathLike(String value) {
            addCriterion("desc_audio_path like", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathNotLike(String value) {
            addCriterion("desc_audio_path not like", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathIn(List<String> values) {
            addCriterion("desc_audio_path in", values, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathNotIn(List<String> values) {
            addCriterion("desc_audio_path not in", values, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathBetween(String value1, String value2) {
            addCriterion("desc_audio_path between", value1, value2, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathNotBetween(String value1, String value2) {
            addCriterion("desc_audio_path not between", value1, value2, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesIsNull() {
            addCriterion("desc_audio_repeat_times is null");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesIsNotNull() {
            addCriterion("desc_audio_repeat_times is not null");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesEqualTo(Integer value) {
            addCriterion("desc_audio_repeat_times =", value, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesNotEqualTo(Integer value) {
            addCriterion("desc_audio_repeat_times <>", value, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesGreaterThan(Integer value) {
            addCriterion("desc_audio_repeat_times >", value, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("desc_audio_repeat_times >=", value, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesLessThan(Integer value) {
            addCriterion("desc_audio_repeat_times <", value, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesLessThanOrEqualTo(Integer value) {
            addCriterion("desc_audio_repeat_times <=", value, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesIn(List<Integer> values) {
            addCriterion("desc_audio_repeat_times in", values, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesNotIn(List<Integer> values) {
            addCriterion("desc_audio_repeat_times not in", values, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesBetween(Integer value1, Integer value2) {
            addCriterion("desc_audio_repeat_times between", value1, value2, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("desc_audio_repeat_times not between", value1, value2, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescWaittimeMillsecondsIsNull() {
            addCriterion("desc_waittime_millseconds is null");
            return (Criteria) this;
        }

        public Criteria andDescWaittimeMillsecondsIsNotNull() {
            addCriterion("desc_waittime_millseconds is not null");
            return (Criteria) this;
        }

        public Criteria andDescWaittimeMillsecondsEqualTo(Long value) {
            addCriterion("desc_waittime_millseconds =", value, "descWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andDescWaittimeMillsecondsNotEqualTo(Long value) {
            addCriterion("desc_waittime_millseconds <>", value, "descWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andDescWaittimeMillsecondsGreaterThan(Long value) {
            addCriterion("desc_waittime_millseconds >", value, "descWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andDescWaittimeMillsecondsGreaterThanOrEqualTo(Long value) {
            addCriterion("desc_waittime_millseconds >=", value, "descWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andDescWaittimeMillsecondsLessThan(Long value) {
            addCriterion("desc_waittime_millseconds <", value, "descWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andDescWaittimeMillsecondsLessThanOrEqualTo(Long value) {
            addCriterion("desc_waittime_millseconds <=", value, "descWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andDescWaittimeMillsecondsIn(List<Long> values) {
            addCriterion("desc_waittime_millseconds in", values, "descWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andDescWaittimeMillsecondsNotIn(List<Long> values) {
            addCriterion("desc_waittime_millseconds not in", values, "descWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andDescWaittimeMillsecondsBetween(Long value1, Long value2) {
            addCriterion("desc_waittime_millseconds between", value1, value2, "descWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andDescWaittimeMillsecondsNotBetween(Long value1, Long value2) {
            addCriterion("desc_waittime_millseconds not between", value1, value2, "descWaittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsIsNull() {
            addCriterion("timeout_millseconds is null");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsIsNotNull() {
            addCriterion("timeout_millseconds is not null");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsEqualTo(Long value) {
            addCriterion("timeout_millseconds =", value, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsNotEqualTo(Long value) {
            addCriterion("timeout_millseconds <>", value, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsGreaterThan(Long value) {
            addCriterion("timeout_millseconds >", value, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsGreaterThanOrEqualTo(Long value) {
            addCriterion("timeout_millseconds >=", value, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsLessThan(Long value) {
            addCriterion("timeout_millseconds <", value, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsLessThanOrEqualTo(Long value) {
            addCriterion("timeout_millseconds <=", value, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsIn(List<Long> values) {
            addCriterion("timeout_millseconds in", values, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsNotIn(List<Long> values) {
            addCriterion("timeout_millseconds not in", values, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsBetween(Long value1, Long value2) {
            addCriterion("timeout_millseconds between", value1, value2, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsNotBetween(Long value1, Long value2) {
            addCriterion("timeout_millseconds not between", value1, value2, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andPassPointsIsNull() {
            addCriterion("pass_points is null");
            return (Criteria) this;
        }

        public Criteria andPassPointsIsNotNull() {
            addCriterion("pass_points is not null");
            return (Criteria) this;
        }

        public Criteria andPassPointsEqualTo(Float value) {
            addCriterion("pass_points =", value, "passPoints");
            return (Criteria) this;
        }

        public Criteria andPassPointsNotEqualTo(Float value) {
            addCriterion("pass_points <>", value, "passPoints");
            return (Criteria) this;
        }

        public Criteria andPassPointsGreaterThan(Float value) {
            addCriterion("pass_points >", value, "passPoints");
            return (Criteria) this;
        }

        public Criteria andPassPointsGreaterThanOrEqualTo(Float value) {
            addCriterion("pass_points >=", value, "passPoints");
            return (Criteria) this;
        }

        public Criteria andPassPointsLessThan(Float value) {
            addCriterion("pass_points <", value, "passPoints");
            return (Criteria) this;
        }

        public Criteria andPassPointsLessThanOrEqualTo(Float value) {
            addCriterion("pass_points <=", value, "passPoints");
            return (Criteria) this;
        }

        public Criteria andPassPointsIn(List<Float> values) {
            addCriterion("pass_points in", values, "passPoints");
            return (Criteria) this;
        }

        public Criteria andPassPointsNotIn(List<Float> values) {
            addCriterion("pass_points not in", values, "passPoints");
            return (Criteria) this;
        }

        public Criteria andPassPointsBetween(Float value1, Float value2) {
            addCriterion("pass_points between", value1, value2, "passPoints");
            return (Criteria) this;
        }

        public Criteria andPassPointsNotBetween(Float value1, Float value2) {
            addCriterion("pass_points not between", value1, value2, "passPoints");
            return (Criteria) this;
        }

        public Criteria andHasOptionIsNull() {
            addCriterion("has_option is null");
            return (Criteria) this;
        }

        public Criteria andHasOptionIsNotNull() {
            addCriterion("has_option is not null");
            return (Criteria) this;
        }

        public Criteria andHasOptionEqualTo(Boolean value) {
            addCriterion("has_option =", value, "hasOption");
            return (Criteria) this;
        }

        public Criteria andHasOptionNotEqualTo(Boolean value) {
            addCriterion("has_option <>", value, "hasOption");
            return (Criteria) this;
        }

        public Criteria andHasOptionGreaterThan(Boolean value) {
            addCriterion("has_option >", value, "hasOption");
            return (Criteria) this;
        }

        public Criteria andHasOptionGreaterThanOrEqualTo(Boolean value) {
            addCriterion("has_option >=", value, "hasOption");
            return (Criteria) this;
        }

        public Criteria andHasOptionLessThan(Boolean value) {
            addCriterion("has_option <", value, "hasOption");
            return (Criteria) this;
        }

        public Criteria andHasOptionLessThanOrEqualTo(Boolean value) {
            addCriterion("has_option <=", value, "hasOption");
            return (Criteria) this;
        }

        public Criteria andHasOptionIn(List<Boolean> values) {
            addCriterion("has_option in", values, "hasOption");
            return (Criteria) this;
        }

        public Criteria andHasOptionNotIn(List<Boolean> values) {
            addCriterion("has_option not in", values, "hasOption");
            return (Criteria) this;
        }

        public Criteria andHasOptionBetween(Boolean value1, Boolean value2) {
            addCriterion("has_option between", value1, value2, "hasOption");
            return (Criteria) this;
        }

        public Criteria andHasOptionNotBetween(Boolean value1, Boolean value2) {
            addCriterion("has_option not between", value1, value2, "hasOption");
            return (Criteria) this;
        }

        public Criteria andRightAnswerIsNull() {
            addCriterion("right_answer is null");
            return (Criteria) this;
        }

        public Criteria andRightAnswerIsNotNull() {
            addCriterion("right_answer is not null");
            return (Criteria) this;
        }

        public Criteria andRightAnswerEqualTo(String value) {
            addCriterion("right_answer =", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerNotEqualTo(String value) {
            addCriterion("right_answer <>", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerGreaterThan(String value) {
            addCriterion("right_answer >", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("right_answer >=", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerLessThan(String value) {
            addCriterion("right_answer <", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerLessThanOrEqualTo(String value) {
            addCriterion("right_answer <=", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerLike(String value) {
            addCriterion("right_answer like", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerNotLike(String value) {
            addCriterion("right_answer not like", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerIn(List<String> values) {
            addCriterion("right_answer in", values, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerNotIn(List<String> values) {
            addCriterion("right_answer not in", values, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerBetween(String value1, String value2) {
            addCriterion("right_answer between", value1, value2, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerNotBetween(String value1, String value2) {
            addCriterion("right_answer not between", value1, value2, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andTotalScoreIsNull() {
            addCriterion("total_score is null");
            return (Criteria) this;
        }

        public Criteria andTotalScoreIsNotNull() {
            addCriterion("total_score is not null");
            return (Criteria) this;
        }

        public Criteria andTotalScoreEqualTo(BigDecimal value) {
            addCriterion("total_score =", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreNotEqualTo(BigDecimal value) {
            addCriterion("total_score <>", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreGreaterThan(BigDecimal value) {
            addCriterion("total_score >", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_score >=", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreLessThan(BigDecimal value) {
            addCriterion("total_score <", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_score <=", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreIn(List<BigDecimal> values) {
            addCriterion("total_score in", values, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreNotIn(List<BigDecimal> values) {
            addCriterion("total_score not in", values, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_score between", value1, value2, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_score not between", value1, value2, "totalScore");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 27 14:21:12 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam_questions_narrow
     *
     * @mbg.generated Tue Sep 27 14:21:12 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}