package com.baoluoge.exam.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExamQuestionAnswerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public ExamQuestionAnswerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdIsNull() {
            addCriterion("exam_questions_narrow_id is null");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdIsNotNull() {
            addCriterion("exam_questions_narrow_id is not null");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdEqualTo(Integer value) {
            addCriterion("exam_questions_narrow_id =", value, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdNotEqualTo(Integer value) {
            addCriterion("exam_questions_narrow_id <>", value, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdGreaterThan(Integer value) {
            addCriterion("exam_questions_narrow_id >", value, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("exam_questions_narrow_id >=", value, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdLessThan(Integer value) {
            addCriterion("exam_questions_narrow_id <", value, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdLessThanOrEqualTo(Integer value) {
            addCriterion("exam_questions_narrow_id <=", value, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdIn(List<Integer> values) {
            addCriterion("exam_questions_narrow_id in", values, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdNotIn(List<Integer> values) {
            addCriterion("exam_questions_narrow_id not in", values, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdBetween(Integer value1, Integer value2) {
            addCriterion("exam_questions_narrow_id between", value1, value2, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdNotBetween(Integer value1, Integer value2) {
            addCriterion("exam_questions_narrow_id not between", value1, value2, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeIsNull() {
            addCriterion("answer_type is null");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeIsNotNull() {
            addCriterion("answer_type is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeEqualTo(Integer value) {
            addCriterion("answer_type =", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeNotEqualTo(Integer value) {
            addCriterion("answer_type <>", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeGreaterThan(Integer value) {
            addCriterion("answer_type >", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("answer_type >=", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeLessThan(Integer value) {
            addCriterion("answer_type <", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeLessThanOrEqualTo(Integer value) {
            addCriterion("answer_type <=", value, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeIn(List<Integer> values) {
            addCriterion("answer_type in", values, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeNotIn(List<Integer> values) {
            addCriterion("answer_type not in", values, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeBetween(Integer value1, Integer value2) {
            addCriterion("answer_type between", value1, value2, "answerType");
            return (Criteria) this;
        }

        public Criteria andAnswerTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("answer_type not between", value1, value2, "answerType");
            return (Criteria) this;
        }

        public Criteria andCodeNumberIsNull() {
            addCriterion("code_number is null");
            return (Criteria) this;
        }

        public Criteria andCodeNumberIsNotNull() {
            addCriterion("code_number is not null");
            return (Criteria) this;
        }

        public Criteria andCodeNumberEqualTo(String value) {
            addCriterion("code_number =", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberNotEqualTo(String value) {
            addCriterion("code_number <>", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberGreaterThan(String value) {
            addCriterion("code_number >", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberGreaterThanOrEqualTo(String value) {
            addCriterion("code_number >=", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberLessThan(String value) {
            addCriterion("code_number <", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberLessThanOrEqualTo(String value) {
            addCriterion("code_number <=", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberLike(String value) {
            addCriterion("code_number like", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberNotLike(String value) {
            addCriterion("code_number not like", value, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberIn(List<String> values) {
            addCriterion("code_number in", values, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberNotIn(List<String> values) {
            addCriterion("code_number not in", values, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberBetween(String value1, String value2) {
            addCriterion("code_number between", value1, value2, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andCodeNumberNotBetween(String value1, String value2) {
            addCriterion("code_number not between", value1, value2, "codeNumber");
            return (Criteria) this;
        }

        public Criteria andDescContentIsNull() {
            addCriterion("desc_content is null");
            return (Criteria) this;
        }

        public Criteria andDescContentIsNotNull() {
            addCriterion("desc_content is not null");
            return (Criteria) this;
        }

        public Criteria andDescContentEqualTo(String value) {
            addCriterion("desc_content =", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentNotEqualTo(String value) {
            addCriterion("desc_content <>", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentGreaterThan(String value) {
            addCriterion("desc_content >", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentGreaterThanOrEqualTo(String value) {
            addCriterion("desc_content >=", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentLessThan(String value) {
            addCriterion("desc_content <", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentLessThanOrEqualTo(String value) {
            addCriterion("desc_content <=", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentLike(String value) {
            addCriterion("desc_content like", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentNotLike(String value) {
            addCriterion("desc_content not like", value, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentIn(List<String> values) {
            addCriterion("desc_content in", values, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentNotIn(List<String> values) {
            addCriterion("desc_content not in", values, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentBetween(String value1, String value2) {
            addCriterion("desc_content between", value1, value2, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescContentNotBetween(String value1, String value2) {
            addCriterion("desc_content not between", value1, value2, "descContent");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlIsNull() {
            addCriterion("desc_img_url is null");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlIsNotNull() {
            addCriterion("desc_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlEqualTo(String value) {
            addCriterion("desc_img_url =", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlNotEqualTo(String value) {
            addCriterion("desc_img_url <>", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlGreaterThan(String value) {
            addCriterion("desc_img_url >", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("desc_img_url >=", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlLessThan(String value) {
            addCriterion("desc_img_url <", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlLessThanOrEqualTo(String value) {
            addCriterion("desc_img_url <=", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlLike(String value) {
            addCriterion("desc_img_url like", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlNotLike(String value) {
            addCriterion("desc_img_url not like", value, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlIn(List<String> values) {
            addCriterion("desc_img_url in", values, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlNotIn(List<String> values) {
            addCriterion("desc_img_url not in", values, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlBetween(String value1, String value2) {
            addCriterion("desc_img_url between", value1, value2, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescImgUrlNotBetween(String value1, String value2) {
            addCriterion("desc_img_url not between", value1, value2, "descImgUrl");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathIsNull() {
            addCriterion("desc_audio_path is null");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathIsNotNull() {
            addCriterion("desc_audio_path is not null");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathEqualTo(String value) {
            addCriterion("desc_audio_path =", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathNotEqualTo(String value) {
            addCriterion("desc_audio_path <>", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathGreaterThan(String value) {
            addCriterion("desc_audio_path >", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathGreaterThanOrEqualTo(String value) {
            addCriterion("desc_audio_path >=", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathLessThan(String value) {
            addCriterion("desc_audio_path <", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathLessThanOrEqualTo(String value) {
            addCriterion("desc_audio_path <=", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathLike(String value) {
            addCriterion("desc_audio_path like", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathNotLike(String value) {
            addCriterion("desc_audio_path not like", value, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathIn(List<String> values) {
            addCriterion("desc_audio_path in", values, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathNotIn(List<String> values) {
            addCriterion("desc_audio_path not in", values, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathBetween(String value1, String value2) {
            addCriterion("desc_audio_path between", value1, value2, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioPathNotBetween(String value1, String value2) {
            addCriterion("desc_audio_path not between", value1, value2, "descAudioPath");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesIsNull() {
            addCriterion("desc_audio_repeat_times is null");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesIsNotNull() {
            addCriterion("desc_audio_repeat_times is not null");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesEqualTo(Integer value) {
            addCriterion("desc_audio_repeat_times =", value, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesNotEqualTo(Integer value) {
            addCriterion("desc_audio_repeat_times <>", value, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesGreaterThan(Integer value) {
            addCriterion("desc_audio_repeat_times >", value, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("desc_audio_repeat_times >=", value, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesLessThan(Integer value) {
            addCriterion("desc_audio_repeat_times <", value, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesLessThanOrEqualTo(Integer value) {
            addCriterion("desc_audio_repeat_times <=", value, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesIn(List<Integer> values) {
            addCriterion("desc_audio_repeat_times in", values, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesNotIn(List<Integer> values) {
            addCriterion("desc_audio_repeat_times not in", values, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesBetween(Integer value1, Integer value2) {
            addCriterion("desc_audio_repeat_times between", value1, value2, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andDescAudioRepeatTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("desc_audio_repeat_times not between", value1, value2, "descAudioRepeatTimes");
            return (Criteria) this;
        }

        public Criteria andValueIsNull() {
            addCriterion("`value` is null");
            return (Criteria) this;
        }

        public Criteria andValueIsNotNull() {
            addCriterion("`value` is not null");
            return (Criteria) this;
        }

        public Criteria andValueEqualTo(String value) {
            addCriterion("`value` =", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotEqualTo(String value) {
            addCriterion("`value` <>", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThan(String value) {
            addCriterion("`value` >", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThanOrEqualTo(String value) {
            addCriterion("`value` >=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThan(String value) {
            addCriterion("`value` <", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThanOrEqualTo(String value) {
            addCriterion("`value` <=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLike(String value) {
            addCriterion("`value` like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotLike(String value) {
            addCriterion("`value` not like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueIn(List<String> values) {
            addCriterion("`value` in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotIn(List<String> values) {
            addCriterion("`value` not in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueBetween(String value1, String value2) {
            addCriterion("`value` between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotBetween(String value1, String value2) {
            addCriterion("`value` not between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andIsRighIsNull() {
            addCriterion("is_righ is null");
            return (Criteria) this;
        }

        public Criteria andIsRighIsNotNull() {
            addCriterion("is_righ is not null");
            return (Criteria) this;
        }

        public Criteria andIsRighEqualTo(Boolean value) {
            addCriterion("is_righ =", value, "isRigh");
            return (Criteria) this;
        }

        public Criteria andIsRighNotEqualTo(Boolean value) {
            addCriterion("is_righ <>", value, "isRigh");
            return (Criteria) this;
        }

        public Criteria andIsRighGreaterThan(Boolean value) {
            addCriterion("is_righ >", value, "isRigh");
            return (Criteria) this;
        }

        public Criteria andIsRighGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_righ >=", value, "isRigh");
            return (Criteria) this;
        }

        public Criteria andIsRighLessThan(Boolean value) {
            addCriterion("is_righ <", value, "isRigh");
            return (Criteria) this;
        }

        public Criteria andIsRighLessThanOrEqualTo(Boolean value) {
            addCriterion("is_righ <=", value, "isRigh");
            return (Criteria) this;
        }

        public Criteria andIsRighIn(List<Boolean> values) {
            addCriterion("is_righ in", values, "isRigh");
            return (Criteria) this;
        }

        public Criteria andIsRighNotIn(List<Boolean> values) {
            addCriterion("is_righ not in", values, "isRigh");
            return (Criteria) this;
        }

        public Criteria andIsRighBetween(Boolean value1, Boolean value2) {
            addCriterion("is_righ between", value1, value2, "isRigh");
            return (Criteria) this;
        }

        public Criteria andIsRighNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_righ not between", value1, value2, "isRigh");
            return (Criteria) this;
        }

        public Criteria andOrderIsNull() {
            addCriterion("`order` is null");
            return (Criteria) this;
        }

        public Criteria andOrderIsNotNull() {
            addCriterion("`order` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderEqualTo(Integer value) {
            addCriterion("`order` =", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotEqualTo(Integer value) {
            addCriterion("`order` <>", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderGreaterThan(Integer value) {
            addCriterion("`order` >", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("`order` >=", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderLessThan(Integer value) {
            addCriterion("`order` <", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderLessThanOrEqualTo(Integer value) {
            addCriterion("`order` <=", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderIn(List<Integer> values) {
            addCriterion("`order` in", values, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotIn(List<Integer> values) {
            addCriterion("`order` not in", values, "order");
            return (Criteria) this;
        }

        public Criteria andOrderBetween(Integer value1, Integer value2) {
            addCriterion("`order` between", value1, value2, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("`order` not between", value1, value2, "order");
            return (Criteria) this;
        }

        public Criteria andWaittimeMillsecondsIsNull() {
            addCriterion("waittime_millseconds is null");
            return (Criteria) this;
        }

        public Criteria andWaittimeMillsecondsIsNotNull() {
            addCriterion("waittime_millseconds is not null");
            return (Criteria) this;
        }

        public Criteria andWaittimeMillsecondsEqualTo(Long value) {
            addCriterion("waittime_millseconds =", value, "waittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andWaittimeMillsecondsNotEqualTo(Long value) {
            addCriterion("waittime_millseconds <>", value, "waittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andWaittimeMillsecondsGreaterThan(Long value) {
            addCriterion("waittime_millseconds >", value, "waittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andWaittimeMillsecondsGreaterThanOrEqualTo(Long value) {
            addCriterion("waittime_millseconds >=", value, "waittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andWaittimeMillsecondsLessThan(Long value) {
            addCriterion("waittime_millseconds <", value, "waittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andWaittimeMillsecondsLessThanOrEqualTo(Long value) {
            addCriterion("waittime_millseconds <=", value, "waittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andWaittimeMillsecondsIn(List<Long> values) {
            addCriterion("waittime_millseconds in", values, "waittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andWaittimeMillsecondsNotIn(List<Long> values) {
            addCriterion("waittime_millseconds not in", values, "waittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andWaittimeMillsecondsBetween(Long value1, Long value2) {
            addCriterion("waittime_millseconds between", value1, value2, "waittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andWaittimeMillsecondsNotBetween(Long value1, Long value2) {
            addCriterion("waittime_millseconds not between", value1, value2, "waittimeMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsIsNull() {
            addCriterion("timeout_millseconds is null");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsIsNotNull() {
            addCriterion("timeout_millseconds is not null");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsEqualTo(Long value) {
            addCriterion("timeout_millseconds =", value, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsNotEqualTo(Long value) {
            addCriterion("timeout_millseconds <>", value, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsGreaterThan(Long value) {
            addCriterion("timeout_millseconds >", value, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsGreaterThanOrEqualTo(Long value) {
            addCriterion("timeout_millseconds >=", value, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsLessThan(Long value) {
            addCriterion("timeout_millseconds <", value, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsLessThanOrEqualTo(Long value) {
            addCriterion("timeout_millseconds <=", value, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsIn(List<Long> values) {
            addCriterion("timeout_millseconds in", values, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsNotIn(List<Long> values) {
            addCriterion("timeout_millseconds not in", values, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsBetween(Long value1, Long value2) {
            addCriterion("timeout_millseconds between", value1, value2, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillsecondsNotBetween(Long value1, Long value2) {
            addCriterion("timeout_millseconds not between", value1, value2, "timeoutMillseconds");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam_question_answer
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 26 10:23:54 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam_question_answer
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}