package com.baoluoge.exam.domain;

import java.math.BigDecimal;
import java.util.Date;

public class ExamPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.id
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.code_number
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private String codeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.name
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.content
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.remark
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.img_url
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.resource_url
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private String resourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.question_count
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private String questionCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.effective_from
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Date effectiveFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.effective_to
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Date effectiveTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.total_score
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private BigDecimal totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.order
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.is_free
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Boolean isFree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.create_time
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.update_time
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.is_delete
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.id
     *
     * @return the value of exam_paper.id
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.id
     *
     * @param id the value for exam_paper.id
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.code_number
     *
     * @return the value of exam_paper.code_number
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public String getCodeNumber() {
        return codeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.code_number
     *
     * @param codeNumber the value for exam_paper.code_number
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setCodeNumber(String codeNumber) {
        this.codeNumber = codeNumber == null ? null : codeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.name
     *
     * @return the value of exam_paper.name
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.name
     *
     * @param name the value for exam_paper.name
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.content
     *
     * @return the value of exam_paper.content
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.content
     *
     * @param content the value for exam_paper.content
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.remark
     *
     * @return the value of exam_paper.remark
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.remark
     *
     * @param remark the value for exam_paper.remark
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.img_url
     *
     * @return the value of exam_paper.img_url
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.img_url
     *
     * @param imgUrl the value for exam_paper.img_url
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.resource_url
     *
     * @return the value of exam_paper.resource_url
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.resource_url
     *
     * @param resourceUrl the value for exam_paper.resource_url
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.question_count
     *
     * @return the value of exam_paper.question_count
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public String getQuestionCount() {
        return questionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.question_count
     *
     * @param questionCount the value for exam_paper.question_count
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setQuestionCount(String questionCount) {
        this.questionCount = questionCount == null ? null : questionCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.effective_from
     *
     * @return the value of exam_paper.effective_from
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Date getEffectiveFrom() {
        return effectiveFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.effective_from
     *
     * @param effectiveFrom the value for exam_paper.effective_from
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.effective_to
     *
     * @return the value of exam_paper.effective_to
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Date getEffectiveTo() {
        return effectiveTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.effective_to
     *
     * @param effectiveTo the value for exam_paper.effective_to
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.total_score
     *
     * @return the value of exam_paper.total_score
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public BigDecimal getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.total_score
     *
     * @param totalScore the value for exam_paper.total_score
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setTotalScore(BigDecimal totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.order
     *
     * @return the value of exam_paper.order
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.order
     *
     * @param order the value for exam_paper.order
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.is_free
     *
     * @return the value of exam_paper.is_free
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Boolean getIsFree() {
        return isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.is_free
     *
     * @param isFree the value for exam_paper.is_free
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setIsFree(Boolean isFree) {
        this.isFree = isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.create_time
     *
     * @return the value of exam_paper.create_time
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.create_time
     *
     * @param createTime the value for exam_paper.create_time
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.update_time
     *
     * @return the value of exam_paper.update_time
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.update_time
     *
     * @param updateTime the value for exam_paper.update_time
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.is_delete
     *
     * @return the value of exam_paper.is_delete
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.is_delete
     *
     * @param isDelete the value for exam_paper.is_delete
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}