package com.baoluoge.exam.domain;

import java.math.BigDecimal;
import java.util.Date;

public class PayGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.id
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.sku
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private String sku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.name
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.body
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private String body;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.month
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private Integer month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.price
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.real_price
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private BigDecimal realPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.discount
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private Float discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.point
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private Integer point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.effective_from
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private Date effectiveFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.effective_to
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private Date effectiveTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.create_time
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.update_time
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_goods.is_delete
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.id
     *
     * @return the value of pay_goods.id
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.id
     *
     * @param id the value for pay_goods.id
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.sku
     *
     * @return the value of pay_goods.sku
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.sku
     *
     * @param sku the value for pay_goods.sku
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.name
     *
     * @return the value of pay_goods.name
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.name
     *
     * @param name the value for pay_goods.name
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.body
     *
     * @return the value of pay_goods.body
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.body
     *
     * @param body the value for pay_goods.body
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.month
     *
     * @return the value of pay_goods.month
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.month
     *
     * @param month the value for pay_goods.month
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.price
     *
     * @return the value of pay_goods.price
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.price
     *
     * @param price the value for pay_goods.price
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.real_price
     *
     * @return the value of pay_goods.real_price
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public BigDecimal getRealPrice() {
        return realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.real_price
     *
     * @param realPrice the value for pay_goods.real_price
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setRealPrice(BigDecimal realPrice) {
        this.realPrice = realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.discount
     *
     * @return the value of pay_goods.discount
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public Float getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.discount
     *
     * @param discount the value for pay_goods.discount
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setDiscount(Float discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.point
     *
     * @return the value of pay_goods.point
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.point
     *
     * @param point the value for pay_goods.point
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.effective_from
     *
     * @return the value of pay_goods.effective_from
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public Date getEffectiveFrom() {
        return effectiveFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.effective_from
     *
     * @param effectiveFrom the value for pay_goods.effective_from
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.effective_to
     *
     * @return the value of pay_goods.effective_to
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public Date getEffectiveTo() {
        return effectiveTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.effective_to
     *
     * @param effectiveTo the value for pay_goods.effective_to
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.create_time
     *
     * @return the value of pay_goods.create_time
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.create_time
     *
     * @param createTime the value for pay_goods.create_time
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.update_time
     *
     * @return the value of pay_goods.update_time
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.update_time
     *
     * @param updateTime the value for pay_goods.update_time
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_goods.is_delete
     *
     * @return the value of pay_goods.is_delete
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_goods.is_delete
     *
     * @param isDelete the value for pay_goods.is_delete
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}