package com.baoluoge.exam.domain;

import java.util.Date;

public class QuestionType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.id
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.order
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Integer order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.code_number
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private String codeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.question_name
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private String questionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.img_url
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.remark
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.create_time
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.update_time
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.is_delete
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.id
     *
     * @return the value of question_type.id
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.id
     *
     * @param id the value for question_type.id
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.order
     *
     * @return the value of question_type.order
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.order
     *
     * @param order the value for question_type.order
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.code_number
     *
     * @return the value of question_type.code_number
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public String getCodeNumber() {
        return codeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.code_number
     *
     * @param codeNumber the value for question_type.code_number
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setCodeNumber(String codeNumber) {
        this.codeNumber = codeNumber == null ? null : codeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.question_name
     *
     * @return the value of question_type.question_name
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public String getQuestionName() {
        return questionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.question_name
     *
     * @param questionName the value for question_type.question_name
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setQuestionName(String questionName) {
        this.questionName = questionName == null ? null : questionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.img_url
     *
     * @return the value of question_type.img_url
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.img_url
     *
     * @param imgUrl the value for question_type.img_url
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.remark
     *
     * @return the value of question_type.remark
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.remark
     *
     * @param remark the value for question_type.remark
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.create_time
     *
     * @return the value of question_type.create_time
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.create_time
     *
     * @param createTime the value for question_type.create_time
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.update_time
     *
     * @return the value of question_type.update_time
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.update_time
     *
     * @param updateTime the value for question_type.update_time
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.is_delete
     *
     * @return the value of question_type.is_delete
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.is_delete
     *
     * @param isDelete the value for question_type.is_delete
     *
     * @mbg.generated Mon Sep 26 10:23:54 CST 2016
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}