package com.baoluoge.exam.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExamWrongHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public UserExamWrongHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdIsNull() {
            addCriterion("exam_paper_id is null");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdIsNotNull() {
            addCriterion("exam_paper_id is not null");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdEqualTo(Integer value) {
            addCriterion("exam_paper_id =", value, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdNotEqualTo(Integer value) {
            addCriterion("exam_paper_id <>", value, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdGreaterThan(Integer value) {
            addCriterion("exam_paper_id >", value, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("exam_paper_id >=", value, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdLessThan(Integer value) {
            addCriterion("exam_paper_id <", value, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdLessThanOrEqualTo(Integer value) {
            addCriterion("exam_paper_id <=", value, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdIn(List<Integer> values) {
            addCriterion("exam_paper_id in", values, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdNotIn(List<Integer> values) {
            addCriterion("exam_paper_id not in", values, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdBetween(Integer value1, Integer value2) {
            addCriterion("exam_paper_id between", value1, value2, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdNotBetween(Integer value1, Integer value2) {
            addCriterion("exam_paper_id not between", value1, value2, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdIsNull() {
            addCriterion("exam_questions_broad_id is null");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdIsNotNull() {
            addCriterion("exam_questions_broad_id is not null");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdEqualTo(Integer value) {
            addCriterion("exam_questions_broad_id =", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdNotEqualTo(Integer value) {
            addCriterion("exam_questions_broad_id <>", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdGreaterThan(Integer value) {
            addCriterion("exam_questions_broad_id >", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("exam_questions_broad_id >=", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdLessThan(Integer value) {
            addCriterion("exam_questions_broad_id <", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdLessThanOrEqualTo(Integer value) {
            addCriterion("exam_questions_broad_id <=", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdIn(List<Integer> values) {
            addCriterion("exam_questions_broad_id in", values, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdNotIn(List<Integer> values) {
            addCriterion("exam_questions_broad_id not in", values, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdBetween(Integer value1, Integer value2) {
            addCriterion("exam_questions_broad_id between", value1, value2, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdNotBetween(Integer value1, Integer value2) {
            addCriterion("exam_questions_broad_id not between", value1, value2, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdIsNull() {
            addCriterion("exam_questions_narrow_id is null");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdIsNotNull() {
            addCriterion("exam_questions_narrow_id is not null");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdEqualTo(Integer value) {
            addCriterion("exam_questions_narrow_id =", value, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdNotEqualTo(Integer value) {
            addCriterion("exam_questions_narrow_id <>", value, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdGreaterThan(Integer value) {
            addCriterion("exam_questions_narrow_id >", value, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("exam_questions_narrow_id >=", value, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdLessThan(Integer value) {
            addCriterion("exam_questions_narrow_id <", value, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdLessThanOrEqualTo(Integer value) {
            addCriterion("exam_questions_narrow_id <=", value, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdIn(List<Integer> values) {
            addCriterion("exam_questions_narrow_id in", values, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdNotIn(List<Integer> values) {
            addCriterion("exam_questions_narrow_id not in", values, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdBetween(Integer value1, Integer value2) {
            addCriterion("exam_questions_narrow_id between", value1, value2, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsNarrowIdNotBetween(Integer value1, Integer value2) {
            addCriterion("exam_questions_narrow_id not between", value1, value2, "examQuestionsNarrowId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdIsNull() {
            addCriterion("questions_type_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdIsNotNull() {
            addCriterion("questions_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdEqualTo(Integer value) {
            addCriterion("questions_type_id =", value, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdNotEqualTo(Integer value) {
            addCriterion("questions_type_id <>", value, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdGreaterThan(Integer value) {
            addCriterion("questions_type_id >", value, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("questions_type_id >=", value, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdLessThan(Integer value) {
            addCriterion("questions_type_id <", value, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("questions_type_id <=", value, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdIn(List<Integer> values) {
            addCriterion("questions_type_id in", values, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdNotIn(List<Integer> values) {
            addCriterion("questions_type_id not in", values, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("questions_type_id between", value1, value2, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("questions_type_id not between", value1, value2, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andIsPassIsNull() {
            addCriterion("is_pass is null");
            return (Criteria) this;
        }

        public Criteria andIsPassIsNotNull() {
            addCriterion("is_pass is not null");
            return (Criteria) this;
        }

        public Criteria andIsPassEqualTo(Boolean value) {
            addCriterion("is_pass =", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotEqualTo(Boolean value) {
            addCriterion("is_pass <>", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassGreaterThan(Boolean value) {
            addCriterion("is_pass >", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_pass >=", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassLessThan(Boolean value) {
            addCriterion("is_pass <", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassLessThanOrEqualTo(Boolean value) {
            addCriterion("is_pass <=", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassIn(List<Boolean> values) {
            addCriterion("is_pass in", values, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotIn(List<Boolean> values) {
            addCriterion("is_pass not in", values, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassBetween(Boolean value1, Boolean value2) {
            addCriterion("is_pass between", value1, value2, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_pass not between", value1, value2, "isPass");
            return (Criteria) this;
        }

        public Criteria andQuestionsTotalScoreIsNull() {
            addCriterion("questions_total_score is null");
            return (Criteria) this;
        }

        public Criteria andQuestionsTotalScoreIsNotNull() {
            addCriterion("questions_total_score is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionsTotalScoreEqualTo(BigDecimal value) {
            addCriterion("questions_total_score =", value, "questionsTotalScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsTotalScoreNotEqualTo(BigDecimal value) {
            addCriterion("questions_total_score <>", value, "questionsTotalScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsTotalScoreGreaterThan(BigDecimal value) {
            addCriterion("questions_total_score >", value, "questionsTotalScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsTotalScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("questions_total_score >=", value, "questionsTotalScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsTotalScoreLessThan(BigDecimal value) {
            addCriterion("questions_total_score <", value, "questionsTotalScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsTotalScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("questions_total_score <=", value, "questionsTotalScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsTotalScoreIn(List<BigDecimal> values) {
            addCriterion("questions_total_score in", values, "questionsTotalScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsTotalScoreNotIn(List<BigDecimal> values) {
            addCriterion("questions_total_score not in", values, "questionsTotalScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsTotalScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("questions_total_score between", value1, value2, "questionsTotalScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsTotalScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("questions_total_score not between", value1, value2, "questionsTotalScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsRealScoreIsNull() {
            addCriterion("questions_real_score is null");
            return (Criteria) this;
        }

        public Criteria andQuestionsRealScoreIsNotNull() {
            addCriterion("questions_real_score is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionsRealScoreEqualTo(BigDecimal value) {
            addCriterion("questions_real_score =", value, "questionsRealScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsRealScoreNotEqualTo(BigDecimal value) {
            addCriterion("questions_real_score <>", value, "questionsRealScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsRealScoreGreaterThan(BigDecimal value) {
            addCriterion("questions_real_score >", value, "questionsRealScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsRealScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("questions_real_score >=", value, "questionsRealScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsRealScoreLessThan(BigDecimal value) {
            addCriterion("questions_real_score <", value, "questionsRealScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsRealScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("questions_real_score <=", value, "questionsRealScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsRealScoreIn(List<BigDecimal> values) {
            addCriterion("questions_real_score in", values, "questionsRealScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsRealScoreNotIn(List<BigDecimal> values) {
            addCriterion("questions_real_score not in", values, "questionsRealScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsRealScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("questions_real_score between", value1, value2, "questionsRealScore");
            return (Criteria) this;
        }

        public Criteria andQuestionsRealScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("questions_real_score not between", value1, value2, "questionsRealScore");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerIsNull() {
            addCriterion("wrong_answer is null");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerIsNotNull() {
            addCriterion("wrong_answer is not null");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerEqualTo(String value) {
            addCriterion("wrong_answer =", value, "wrongAnswer");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerNotEqualTo(String value) {
            addCriterion("wrong_answer <>", value, "wrongAnswer");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerGreaterThan(String value) {
            addCriterion("wrong_answer >", value, "wrongAnswer");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("wrong_answer >=", value, "wrongAnswer");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerLessThan(String value) {
            addCriterion("wrong_answer <", value, "wrongAnswer");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerLessThanOrEqualTo(String value) {
            addCriterion("wrong_answer <=", value, "wrongAnswer");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerLike(String value) {
            addCriterion("wrong_answer like", value, "wrongAnswer");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerNotLike(String value) {
            addCriterion("wrong_answer not like", value, "wrongAnswer");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerIn(List<String> values) {
            addCriterion("wrong_answer in", values, "wrongAnswer");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerNotIn(List<String> values) {
            addCriterion("wrong_answer not in", values, "wrongAnswer");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerBetween(String value1, String value2) {
            addCriterion("wrong_answer between", value1, value2, "wrongAnswer");
            return (Criteria) this;
        }

        public Criteria andWrongAnswerNotBetween(String value1, String value2) {
            addCriterion("wrong_answer not between", value1, value2, "wrongAnswer");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathIsNull() {
            addCriterion("wrong_audio_path is null");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathIsNotNull() {
            addCriterion("wrong_audio_path is not null");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathEqualTo(String value) {
            addCriterion("wrong_audio_path =", value, "wrongAudioPath");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathNotEqualTo(String value) {
            addCriterion("wrong_audio_path <>", value, "wrongAudioPath");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathGreaterThan(String value) {
            addCriterion("wrong_audio_path >", value, "wrongAudioPath");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathGreaterThanOrEqualTo(String value) {
            addCriterion("wrong_audio_path >=", value, "wrongAudioPath");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathLessThan(String value) {
            addCriterion("wrong_audio_path <", value, "wrongAudioPath");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathLessThanOrEqualTo(String value) {
            addCriterion("wrong_audio_path <=", value, "wrongAudioPath");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathLike(String value) {
            addCriterion("wrong_audio_path like", value, "wrongAudioPath");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathNotLike(String value) {
            addCriterion("wrong_audio_path not like", value, "wrongAudioPath");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathIn(List<String> values) {
            addCriterion("wrong_audio_path in", values, "wrongAudioPath");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathNotIn(List<String> values) {
            addCriterion("wrong_audio_path not in", values, "wrongAudioPath");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathBetween(String value1, String value2) {
            addCriterion("wrong_audio_path between", value1, value2, "wrongAudioPath");
            return (Criteria) this;
        }

        public Criteria andWrongAudioPathNotBetween(String value1, String value2) {
            addCriterion("wrong_audio_path not between", value1, value2, "wrongAudioPath");
            return (Criteria) this;
        }

        public Criteria andWrongCommentIsNull() {
            addCriterion("wrong_comment is null");
            return (Criteria) this;
        }

        public Criteria andWrongCommentIsNotNull() {
            addCriterion("wrong_comment is not null");
            return (Criteria) this;
        }

        public Criteria andWrongCommentEqualTo(String value) {
            addCriterion("wrong_comment =", value, "wrongComment");
            return (Criteria) this;
        }

        public Criteria andWrongCommentNotEqualTo(String value) {
            addCriterion("wrong_comment <>", value, "wrongComment");
            return (Criteria) this;
        }

        public Criteria andWrongCommentGreaterThan(String value) {
            addCriterion("wrong_comment >", value, "wrongComment");
            return (Criteria) this;
        }

        public Criteria andWrongCommentGreaterThanOrEqualTo(String value) {
            addCriterion("wrong_comment >=", value, "wrongComment");
            return (Criteria) this;
        }

        public Criteria andWrongCommentLessThan(String value) {
            addCriterion("wrong_comment <", value, "wrongComment");
            return (Criteria) this;
        }

        public Criteria andWrongCommentLessThanOrEqualTo(String value) {
            addCriterion("wrong_comment <=", value, "wrongComment");
            return (Criteria) this;
        }

        public Criteria andWrongCommentLike(String value) {
            addCriterion("wrong_comment like", value, "wrongComment");
            return (Criteria) this;
        }

        public Criteria andWrongCommentNotLike(String value) {
            addCriterion("wrong_comment not like", value, "wrongComment");
            return (Criteria) this;
        }

        public Criteria andWrongCommentIn(List<String> values) {
            addCriterion("wrong_comment in", values, "wrongComment");
            return (Criteria) this;
        }

        public Criteria andWrongCommentNotIn(List<String> values) {
            addCriterion("wrong_comment not in", values, "wrongComment");
            return (Criteria) this;
        }

        public Criteria andWrongCommentBetween(String value1, String value2) {
            addCriterion("wrong_comment between", value1, value2, "wrongComment");
            return (Criteria) this;
        }

        public Criteria andWrongCommentNotBetween(String value1, String value2) {
            addCriterion("wrong_comment not between", value1, value2, "wrongComment");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 21 15:22:26 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_exam_wrong_history
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}