package com.baoluoge.exam.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserLearnLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public UserLearnLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andLearnTypeIsNull() {
            addCriterion("learn_type is null");
            return (Criteria) this;
        }

        public Criteria andLearnTypeIsNotNull() {
            addCriterion("learn_type is not null");
            return (Criteria) this;
        }

        public Criteria andLearnTypeEqualTo(Integer value) {
            addCriterion("learn_type =", value, "learnType");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNotEqualTo(Integer value) {
            addCriterion("learn_type <>", value, "learnType");
            return (Criteria) this;
        }

        public Criteria andLearnTypeGreaterThan(Integer value) {
            addCriterion("learn_type >", value, "learnType");
            return (Criteria) this;
        }

        public Criteria andLearnTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("learn_type >=", value, "learnType");
            return (Criteria) this;
        }

        public Criteria andLearnTypeLessThan(Integer value) {
            addCriterion("learn_type <", value, "learnType");
            return (Criteria) this;
        }

        public Criteria andLearnTypeLessThanOrEqualTo(Integer value) {
            addCriterion("learn_type <=", value, "learnType");
            return (Criteria) this;
        }

        public Criteria andLearnTypeIn(List<Integer> values) {
            addCriterion("learn_type in", values, "learnType");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNotIn(List<Integer> values) {
            addCriterion("learn_type not in", values, "learnType");
            return (Criteria) this;
        }

        public Criteria andLearnTypeBetween(Integer value1, Integer value2) {
            addCriterion("learn_type between", value1, value2, "learnType");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("learn_type not between", value1, value2, "learnType");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameIsNull() {
            addCriterion("learn_type_name is null");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameIsNotNull() {
            addCriterion("learn_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameEqualTo(String value) {
            addCriterion("learn_type_name =", value, "learnTypeName");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameNotEqualTo(String value) {
            addCriterion("learn_type_name <>", value, "learnTypeName");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameGreaterThan(String value) {
            addCriterion("learn_type_name >", value, "learnTypeName");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("learn_type_name >=", value, "learnTypeName");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameLessThan(String value) {
            addCriterion("learn_type_name <", value, "learnTypeName");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameLessThanOrEqualTo(String value) {
            addCriterion("learn_type_name <=", value, "learnTypeName");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameLike(String value) {
            addCriterion("learn_type_name like", value, "learnTypeName");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameNotLike(String value) {
            addCriterion("learn_type_name not like", value, "learnTypeName");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameIn(List<String> values) {
            addCriterion("learn_type_name in", values, "learnTypeName");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameNotIn(List<String> values) {
            addCriterion("learn_type_name not in", values, "learnTypeName");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameBetween(String value1, String value2) {
            addCriterion("learn_type_name between", value1, value2, "learnTypeName");
            return (Criteria) this;
        }

        public Criteria andLearnTypeNameNotBetween(String value1, String value2) {
            addCriterion("learn_type_name not between", value1, value2, "learnTypeName");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLIsNull() {
            addCriterion("learn_source_name_l is null");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLIsNotNull() {
            addCriterion("learn_source_name_l is not null");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLEqualTo(String value) {
            addCriterion("learn_source_name_l =", value, "learnSourceNameL");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLNotEqualTo(String value) {
            addCriterion("learn_source_name_l <>", value, "learnSourceNameL");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLGreaterThan(String value) {
            addCriterion("learn_source_name_l >", value, "learnSourceNameL");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLGreaterThanOrEqualTo(String value) {
            addCriterion("learn_source_name_l >=", value, "learnSourceNameL");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLLessThan(String value) {
            addCriterion("learn_source_name_l <", value, "learnSourceNameL");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLLessThanOrEqualTo(String value) {
            addCriterion("learn_source_name_l <=", value, "learnSourceNameL");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLLike(String value) {
            addCriterion("learn_source_name_l like", value, "learnSourceNameL");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLNotLike(String value) {
            addCriterion("learn_source_name_l not like", value, "learnSourceNameL");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLIn(List<String> values) {
            addCriterion("learn_source_name_l in", values, "learnSourceNameL");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLNotIn(List<String> values) {
            addCriterion("learn_source_name_l not in", values, "learnSourceNameL");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLBetween(String value1, String value2) {
            addCriterion("learn_source_name_l between", value1, value2, "learnSourceNameL");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameLNotBetween(String value1, String value2) {
            addCriterion("learn_source_name_l not between", value1, value2, "learnSourceNameL");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSIsNull() {
            addCriterion("learn_source_name_s is null");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSIsNotNull() {
            addCriterion("learn_source_name_s is not null");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSEqualTo(String value) {
            addCriterion("learn_source_name_s =", value, "learnSourceNameS");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSNotEqualTo(String value) {
            addCriterion("learn_source_name_s <>", value, "learnSourceNameS");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSGreaterThan(String value) {
            addCriterion("learn_source_name_s >", value, "learnSourceNameS");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSGreaterThanOrEqualTo(String value) {
            addCriterion("learn_source_name_s >=", value, "learnSourceNameS");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSLessThan(String value) {
            addCriterion("learn_source_name_s <", value, "learnSourceNameS");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSLessThanOrEqualTo(String value) {
            addCriterion("learn_source_name_s <=", value, "learnSourceNameS");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSLike(String value) {
            addCriterion("learn_source_name_s like", value, "learnSourceNameS");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSNotLike(String value) {
            addCriterion("learn_source_name_s not like", value, "learnSourceNameS");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSIn(List<String> values) {
            addCriterion("learn_source_name_s in", values, "learnSourceNameS");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSNotIn(List<String> values) {
            addCriterion("learn_source_name_s not in", values, "learnSourceNameS");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSBetween(String value1, String value2) {
            addCriterion("learn_source_name_s between", value1, value2, "learnSourceNameS");
            return (Criteria) this;
        }

        public Criteria andLearnSourceNameSNotBetween(String value1, String value2) {
            addCriterion("learn_source_name_s not between", value1, value2, "learnSourceNameS");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(BigDecimal value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(BigDecimal value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(BigDecimal value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(BigDecimal value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<BigDecimal> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<BigDecimal> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdIsNull() {
            addCriterion("exam_paper_id is null");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdIsNotNull() {
            addCriterion("exam_paper_id is not null");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdEqualTo(Integer value) {
            addCriterion("exam_paper_id =", value, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdNotEqualTo(Integer value) {
            addCriterion("exam_paper_id <>", value, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdGreaterThan(Integer value) {
            addCriterion("exam_paper_id >", value, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("exam_paper_id >=", value, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdLessThan(Integer value) {
            addCriterion("exam_paper_id <", value, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdLessThanOrEqualTo(Integer value) {
            addCriterion("exam_paper_id <=", value, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdIn(List<Integer> values) {
            addCriterion("exam_paper_id in", values, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdNotIn(List<Integer> values) {
            addCriterion("exam_paper_id not in", values, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdBetween(Integer value1, Integer value2) {
            addCriterion("exam_paper_id between", value1, value2, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamPaperIdNotBetween(Integer value1, Integer value2) {
            addCriterion("exam_paper_id not between", value1, value2, "examPaperId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdIsNull() {
            addCriterion("exam_questions_broad_id is null");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdIsNotNull() {
            addCriterion("exam_questions_broad_id is not null");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdEqualTo(Integer value) {
            addCriterion("exam_questions_broad_id =", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdNotEqualTo(Integer value) {
            addCriterion("exam_questions_broad_id <>", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdGreaterThan(Integer value) {
            addCriterion("exam_questions_broad_id >", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("exam_questions_broad_id >=", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdLessThan(Integer value) {
            addCriterion("exam_questions_broad_id <", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdLessThanOrEqualTo(Integer value) {
            addCriterion("exam_questions_broad_id <=", value, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdIn(List<Integer> values) {
            addCriterion("exam_questions_broad_id in", values, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdNotIn(List<Integer> values) {
            addCriterion("exam_questions_broad_id not in", values, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdBetween(Integer value1, Integer value2) {
            addCriterion("exam_questions_broad_id between", value1, value2, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andExamQuestionsBroadIdNotBetween(Integer value1, Integer value2) {
            addCriterion("exam_questions_broad_id not between", value1, value2, "examQuestionsBroadId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdIsNull() {
            addCriterion("questions_type_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdIsNotNull() {
            addCriterion("questions_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdEqualTo(Integer value) {
            addCriterion("questions_type_id =", value, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdNotEqualTo(Integer value) {
            addCriterion("questions_type_id <>", value, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdGreaterThan(Integer value) {
            addCriterion("questions_type_id >", value, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("questions_type_id >=", value, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdLessThan(Integer value) {
            addCriterion("questions_type_id <", value, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("questions_type_id <=", value, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdIn(List<Integer> values) {
            addCriterion("questions_type_id in", values, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdNotIn(List<Integer> values) {
            addCriterion("questions_type_id not in", values, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("questions_type_id between", value1, value2, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andQuestionsTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("questions_type_id not between", value1, value2, "questionsTypeId");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsIsNull() {
            addCriterion("user_exam_wrong_history_ids is null");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsIsNotNull() {
            addCriterion("user_exam_wrong_history_ids is not null");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsEqualTo(String value) {
            addCriterion("user_exam_wrong_history_ids =", value, "userExamWrongHistoryIds");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsNotEqualTo(String value) {
            addCriterion("user_exam_wrong_history_ids <>", value, "userExamWrongHistoryIds");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsGreaterThan(String value) {
            addCriterion("user_exam_wrong_history_ids >", value, "userExamWrongHistoryIds");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsGreaterThanOrEqualTo(String value) {
            addCriterion("user_exam_wrong_history_ids >=", value, "userExamWrongHistoryIds");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsLessThan(String value) {
            addCriterion("user_exam_wrong_history_ids <", value, "userExamWrongHistoryIds");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsLessThanOrEqualTo(String value) {
            addCriterion("user_exam_wrong_history_ids <=", value, "userExamWrongHistoryIds");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsLike(String value) {
            addCriterion("user_exam_wrong_history_ids like", value, "userExamWrongHistoryIds");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsNotLike(String value) {
            addCriterion("user_exam_wrong_history_ids not like", value, "userExamWrongHistoryIds");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsIn(List<String> values) {
            addCriterion("user_exam_wrong_history_ids in", values, "userExamWrongHistoryIds");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsNotIn(List<String> values) {
            addCriterion("user_exam_wrong_history_ids not in", values, "userExamWrongHistoryIds");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsBetween(String value1, String value2) {
            addCriterion("user_exam_wrong_history_ids between", value1, value2, "userExamWrongHistoryIds");
            return (Criteria) this;
        }

        public Criteria andUserExamWrongHistoryIdsNotBetween(String value1, String value2) {
            addCriterion("user_exam_wrong_history_ids not between", value1, value2, "userExamWrongHistoryIds");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNull() {
            addCriterion("begin_time is null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNotNull() {
            addCriterion("begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeEqualTo(Date value) {
            addCriterion("begin_time =", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotEqualTo(Date value) {
            addCriterion("begin_time <>", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThan(Date value) {
            addCriterion("begin_time >", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("begin_time >=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThan(Date value) {
            addCriterion("begin_time <", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("begin_time <=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIn(List<Date> values) {
            addCriterion("begin_time in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotIn(List<Date> values) {
            addCriterion("begin_time not in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeBetween(Date value1, Date value2) {
            addCriterion("begin_time between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("begin_time not between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_learn_log
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 13 17:56:06 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_learn_log
     *
     * @mbg.generated Thu Oct 13 17:56:06 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}