package com.baoluoge.exam.domain;

import java.math.BigDecimal;
import java.util.Date;

public class UserExamWrongHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.exam_paper_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private Integer examPaperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.exam_questions_broad_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private Integer examQuestionsBroadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.exam_questions_narrow_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private Integer examQuestionsNarrowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.questions_type_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private Integer questionsTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.user_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.is_pass
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private Boolean isPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.questions_total_score
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private BigDecimal questionsTotalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.questions_real_score
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private BigDecimal questionsRealScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.wrong_answer
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private String wrongAnswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.wrong_audio_path
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private String wrongAudioPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.wrong_comment
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private String wrongComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.create_time
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.update_time
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.is_delete
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_exam_wrong_history.wrong_result
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    private String wrongResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.id
     *
     * @return the value of user_exam_wrong_history.id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.id
     *
     * @param id the value for user_exam_wrong_history.id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.exam_paper_id
     *
     * @return the value of user_exam_wrong_history.exam_paper_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public Integer getExamPaperId() {
        return examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.exam_paper_id
     *
     * @param examPaperId the value for user_exam_wrong_history.exam_paper_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setExamPaperId(Integer examPaperId) {
        this.examPaperId = examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.exam_questions_broad_id
     *
     * @return the value of user_exam_wrong_history.exam_questions_broad_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public Integer getExamQuestionsBroadId() {
        return examQuestionsBroadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.exam_questions_broad_id
     *
     * @param examQuestionsBroadId the value for user_exam_wrong_history.exam_questions_broad_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setExamQuestionsBroadId(Integer examQuestionsBroadId) {
        this.examQuestionsBroadId = examQuestionsBroadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.exam_questions_narrow_id
     *
     * @return the value of user_exam_wrong_history.exam_questions_narrow_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public Integer getExamQuestionsNarrowId() {
        return examQuestionsNarrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.exam_questions_narrow_id
     *
     * @param examQuestionsNarrowId the value for user_exam_wrong_history.exam_questions_narrow_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setExamQuestionsNarrowId(Integer examQuestionsNarrowId) {
        this.examQuestionsNarrowId = examQuestionsNarrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.questions_type_id
     *
     * @return the value of user_exam_wrong_history.questions_type_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public Integer getQuestionsTypeId() {
        return questionsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.questions_type_id
     *
     * @param questionsTypeId the value for user_exam_wrong_history.questions_type_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setQuestionsTypeId(Integer questionsTypeId) {
        this.questionsTypeId = questionsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.user_id
     *
     * @return the value of user_exam_wrong_history.user_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.user_id
     *
     * @param userId the value for user_exam_wrong_history.user_id
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.is_pass
     *
     * @return the value of user_exam_wrong_history.is_pass
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public Boolean getIsPass() {
        return isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.is_pass
     *
     * @param isPass the value for user_exam_wrong_history.is_pass
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setIsPass(Boolean isPass) {
        this.isPass = isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.questions_total_score
     *
     * @return the value of user_exam_wrong_history.questions_total_score
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public BigDecimal getQuestionsTotalScore() {
        return questionsTotalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.questions_total_score
     *
     * @param questionsTotalScore the value for user_exam_wrong_history.questions_total_score
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setQuestionsTotalScore(BigDecimal questionsTotalScore) {
        this.questionsTotalScore = questionsTotalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.questions_real_score
     *
     * @return the value of user_exam_wrong_history.questions_real_score
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public BigDecimal getQuestionsRealScore() {
        return questionsRealScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.questions_real_score
     *
     * @param questionsRealScore the value for user_exam_wrong_history.questions_real_score
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setQuestionsRealScore(BigDecimal questionsRealScore) {
        this.questionsRealScore = questionsRealScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.wrong_answer
     *
     * @return the value of user_exam_wrong_history.wrong_answer
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public String getWrongAnswer() {
        return wrongAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.wrong_answer
     *
     * @param wrongAnswer the value for user_exam_wrong_history.wrong_answer
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setWrongAnswer(String wrongAnswer) {
        this.wrongAnswer = wrongAnswer == null ? null : wrongAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.wrong_audio_path
     *
     * @return the value of user_exam_wrong_history.wrong_audio_path
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public String getWrongAudioPath() {
        return wrongAudioPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.wrong_audio_path
     *
     * @param wrongAudioPath the value for user_exam_wrong_history.wrong_audio_path
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setWrongAudioPath(String wrongAudioPath) {
        this.wrongAudioPath = wrongAudioPath == null ? null : wrongAudioPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.wrong_comment
     *
     * @return the value of user_exam_wrong_history.wrong_comment
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public String getWrongComment() {
        return wrongComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.wrong_comment
     *
     * @param wrongComment the value for user_exam_wrong_history.wrong_comment
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setWrongComment(String wrongComment) {
        this.wrongComment = wrongComment == null ? null : wrongComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.create_time
     *
     * @return the value of user_exam_wrong_history.create_time
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.create_time
     *
     * @param createTime the value for user_exam_wrong_history.create_time
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.update_time
     *
     * @return the value of user_exam_wrong_history.update_time
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.update_time
     *
     * @param updateTime the value for user_exam_wrong_history.update_time
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.is_delete
     *
     * @return the value of user_exam_wrong_history.is_delete
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.is_delete
     *
     * @param isDelete the value for user_exam_wrong_history.is_delete
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_exam_wrong_history.wrong_result
     *
     * @return the value of user_exam_wrong_history.wrong_result
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public String getWrongResult() {
        return wrongResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_exam_wrong_history.wrong_result
     *
     * @param wrongResult the value for user_exam_wrong_history.wrong_result
     *
     * @mbg.generated Fri Oct 21 15:22:26 CST 2016
     */
    public void setWrongResult(String wrongResult) {
        this.wrongResult = wrongResult == null ? null : wrongResult.trim();
    }
}